- name: Restrict SSH logins to keys only
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'

- name: Restrict SSH logins to keys only regex2
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: absent
    regexp: '^#PasswordAuthentication'
    line: 'PasswordAuthentication no'


- name: Restart sshd
  service: name=sshd state=restarted enabled=yes

